const actionTypes = {
  LOAD_NOW_PLAYING: 'LOAD_NOW_PLAYING',
  LOAD_NOW_PLAYING_ERROR: 'LOAD_NOW_PLAYING_ERROR',
  LOAD_MOVIE_BY_SEARCH: 'LOAD_MOVIE_BY_SEARCH',
  LOAD_MOVIE_BY_SEARCH_ERROR: 'LOAD_MOVIE_BY_SEARCH_ERROR',
  SAVE_QUERY: 'SAVE_QUERY',
  LOAD_POPULAR: 'LOAD_POPULAR',
  LOAD_POPULAR_ERROR: 'LOAD_POPULAR_ERROR',
  LOAD_UPCOMMING: 'LOAD_UPCOMMING',
  LOAD_UPCOMMING_ERROR: 'LOAD_UPCOMMING_ERROR',

};

export default actionTypes;
