const actionTypes = {
  LOAD_MOVIE_BY_SEARCH: 'LOAD_MOVIE_BY_SEARCH',
  LOAD_MOVIE_BY_SEARCH_ERROR: 'LOAD_MOVIE_BY_SEARCH_ERROR',
  SAVE_QUERY: 'SAVE_QUERY',
  LOAD_MOVIES_ERROR: 'LOAD_MOVIES_ERROR',
  LOAD_MOVIES: 'LOAD_MOVIES',
  LOAD_SIMILAR: 'LOAD_SIMILAR',
  LOAD_SIMILAR_ERROR: 'LOAD_SIMILAR_ERROR',
  LOAD_VIDEO: 'LOAD_VIDEO',
  LOAD_VIDEO_ERROR: 'LOAD_VIDEO_ERROR',
};

export default actionTypes;
